### ISSUE TITLE
Feature Request: Multiple Masks

### ISSUE THREAD

**Issue by fjb80** [aeag/mask#65]
I'm working on a large mapping project that has 3 focus areas. Currently using the Mask plugin (which is great btw) I can only create one mask in the "Master" File. If I want to mask Area 1 it works great. I set up the mask and export to pdf from the print composer. However, once I want to export Area 2, the only way that seems to work is to delete the original mask and create a new mask (or update) and go through the whole process again of applying a style, etc.

It would be great if I could have 3 different mask files that I could just turn on and off with each Area.

Unless I'm missing an easier way to do this, but from what I can see you can only have 1 mask per qgis file.

Thanks.

**Comment by xcaeag** [comment]
Hi,

Removing the atlas layer is not necessary, just select a new polygon and reapply the atlas. The style will be preserved.

But the simplest way is to use (in composer) the Atlas feature, combined with mask. The tool allows you to export a page (image, pdf) for each entity by looping and making a mask for each.
Otherwise, in a "static" way, you can apply a "mask" style (inverted polygon) to any layer.

You can find severals tutorials about atlas plugin.
A tutorial here : https://www.youtube.com/watch?v=698BZcblGi4
