### ISSUE TITLE
Installation error  in QGIS 3.1

### ISSUE THREAD

**Issue by davidnfox** [aeag/mask#66]
When installing;
ImportError: cannot import name 'QgsAtlasComposition'

**Comment by fgfletcher** [comment]
Attempt to load the plugin into QGIS version | 3.6.3-Noosa results in the following error:

Couldn't load plugin 'mask' due to an error when calling its initGui() method 

TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout' 
Traceback (most recent call last):
  File "/Applications/QGIS_3_6_3-1.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mask/aeag_mask.py", line 227, in initGui
    self.on_layout_added(layout)
  File "/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mask/aeag_mask.py", line 350, in on_layout_added
    layout = QgsProject.instance().layoutManager().layoutByName(layoutName)
TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout'


Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.6.3-Noosa Noosa, exported 

Python Path:
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pdaltools
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LAStools
/Applications/QGIS_3_6_3-1.app/Contents/MacOS/../Resources/python
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS_3_6_3-1.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin
/Users/garthfletcher/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder
/Users/garthfletcher/GPS MASON/  QGIS PROJECTS
