### ISSUE TITLE
Using the mask with Reports

### ISSUE THREAD

**Issue by LouHennenfent** [aeag/mask#98]
I have a problem when I want to use the mask extension with the report fonctionnality.
It seems like it's not possible for the features of the map to be filtered by the mask based on the report layer.

**Comment by xcaeag** [comment]
indeed, the plugin was not designed to work with reports.

This extension being in fact only an assistant, you can do without it.

Look at the page http://aeag.github.io/mask/, "an alternative...".

The principle :
- duplicate the layer you want to mask (the same one you use in the report or the atlas),
- give it an 'inverted polygon' style
- choose a 'rule based' rendering engine in order to filter the layer as follows:
   attribute($currentfeature, 'the_primary_key_field') = attribute(@atlas_feature , 'the_primary_key_field')

Thus, only the feature corresponding to the current feature of the group report will be displayed.

And displaying only the labels of the mask could be done by the expression "contains(@atlas_geometry, $geometry)" placed in the labeling option 'show label'...

Hoping to have understood your problem!
If necessary, I can try to produce an animation...

**Comment by LouHennenfent** [comment]
Thanks for the explaination ! I don't know why I couldn't make it work with your expression, but I found one that works : @atlas_featureid= "fid"
